In [1]:
import numpy as np

### 1. Covariance Matrix 계산

In [8]:
a = np.array([[170, 60, 4.1],
              [165, 55, 3.0],
              [174, 75, 2.8],
              [169, 67, 2.9],
              [155, 49, 3.1],
              [172, 63, 3.6],
              [166, 58, 3.7],
              [168, 61, 4.0]])

m = np.mean(a, axis=0)
a -= m

In [9]:
print(a.T @ a / (len(a)-1))

[[33.69642857 39.42857143  0.37142857]
 [39.42857143 60.85714286 -0.94285714]
 [ 0.37142857 -0.94285714  0.26285714]]
